# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c290d137c22c0f9c996fd8d20959612131e8d2206899fc25821cfff36c88faeb4388559b12bb3c4640195f84aea5003e7ed05b95b82f530e3c78ae15c6a226e0

test:
  secret_key_base: 3469f46cd1e2919aae66f54746d319de7827dbe4f95c9b32753bfd474636b3fe784220bb27534db8e184ba1f7f13d6e1714dc1540f278f1b7ee32ff7838b5454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
